/**
 * API barrel — re-exports everything for backward compatibility.
 *
 * Existing imports like `import { fetchProjectConfig } from '../lib/api'`
 * will continue to work because this file re-exports all symbols.
 *
 * New code should prefer importing from specific modules:
 *   import { fetchProjectConfig } from '../lib/api/project';
 *   import { encodeProjectDir } from '../lib/api/client';
 *   import type { Job } from '../lib/api/types';
 */

// ---- Types ----
export type {
  ConnectionPhase,
  JobStatus,
  TranslatorOption,
  Job,
  PromptTemplateOverride,
  SubmitJobPayload,
  TranslatorsResponse,
  JobsResponse,
  ErrorResponse,
  ProjectConfigTemplateResponse,
  ProjectConfigResponse,
  ConfigSchemaResponse,
  ProjectConfigUpdatePayload,
  FileEntry,
  ProjectFilesResponse,
  CacheFileResponse,
  CacheEntry,
  CacheSearchField,
  CacheSearchResult,
  CacheSearchResponse,
  CacheReplaceField,
  CacheReplaceFileDetail,
  CacheReplaceResponse,
  FileProgress,
  ProjectProgressResponse,
  RuntimeJob,
  ProjectRuntimeSummary,
  ProjectRuntimeErrorEntry,
  ProjectRuntimeSuccessEntry,
  ProjectRetranslStatEntry,
  ProjectRuntimeResponse,
  StopProjectResponse,
  DictFileContent,
  ProjectDictionaryResponse,
  DictionaryCategory,
  ProjectDictionaryManagerResponse,
  CommonDictionaryManagerResponse,
  ProblemEntry,
  ProjectProblemsResponse,
  NameEntry,
  NameTableResponse,
  NameTableGenerateResponse,
  NameTableSaveResponse,
  NameDictResponse,
  ProjectLogsResponse,
  PluginInfo,
  AppSettings,
  ThemeMode,
  CustomBackgroundPreference,
  PluginsResponse,
  ProblemTypeInfo,
  ProblemTypesResponse,
  PromptTemplateInfo,
  PromptTemplatesResponse,
  VersionCheckResponse,
  BackendProfilesResponse,
  BackendProfileResponse,
  BackendProfilesMap,
  FetchOpenAIModelsPayload,
  FetchOpenAIModelsResponse,
} from './types';

// ---- Client ----
export { ApiError, encodeProjectDir, decodeProjectDir, ensureDesktopBackendReady, setRuntimeBackendBaseUrl } from './client';

// ---- General API ----
export {
  fetchVersion,
  fetchVersionCheck,
  fetchTranslators,
  fetchJobs,
  fetchJob,
  submitJob,
  fetchPlugins,
  fetchProblemTypes,
  fetchTranslationGuidelines,
  fetchAppSettings,
  updateAppSettings,
  fetchDefaultProjectConfigTemplate,
  fetchPromptTemplates,
  fetchOpenAIModels,
} from './general';

// ---- Project API ----
export {
  fetchProjectConfig,
  updateProjectConfig,
  fetchConfigSchema,
  fetchProjectFiles,
  fetchProjectCache,
  fetchCacheFile,
  saveCacheFile,
  deleteCacheEntry,
  deleteCacheFiles,
  searchCache,
  replaceCache,
  fetchProjectProgress,
  fetchProjectRuntime,
  stopProjectTranslation,
  fetchProjectDictionary,
  fetchProjectDictionaryManager,
  createProjectDictionaryFile,
  saveProjectDictionaryFile,
  deleteProjectDictionaryFile,
  fetchCommonDictionaryManager,
  createCommonDictionaryFile,
  saveCommonDictionaryFile,
  deleteCommonDictionaryFile,
  fetchProjectProblems,
  fetchNameTable,
  generateNameTable,
  saveNameTable,
  getAiTranslateUrl,
  fetchNameDict,
  fetchProjectLogs,
} from './project';

// ---- Preferences ----
export {
  HOME_HISTORY_LIMIT_DEFAULT,
  HOME_JOB_LIMIT_DEFAULT,
  HOME_LIST_LIMIT_MIN,
  HOME_LIST_LIMIT_MAX,
  CUSTOM_BACKGROUND_OPACITY_MIN,
  CUSTOM_BACKGROUND_OPACITY_MAX,
  CUSTOM_BACKGROUND_OPACITY_DEFAULT,
  CUSTOM_BACKGROUND_SURFACE_OPACITY_MIN,
  CUSTOM_BACKGROUND_SURFACE_OPACITY_MAX,
  CUSTOM_BACKGROUND_SURFACE_OPACITY_DEFAULT,
  HIDE_BACKEND_CONSOLE_DEFAULT,
  CACHE_BROWSER_FONT_SIZE_MIN,
  CACHE_BROWSER_FONT_SIZE_MAX,
  CACHE_BROWSER_FONT_SIZE_DEFAULT,
  BACKEND_PROFILES_CHANGE_EVENT,
  DEFAULT_BACKEND_PROFILE_CHANGE_EVENT,
  HOME_HISTORY_LIMIT_CHANGE_EVENT,
  HOME_JOB_LIMIT_CHANGE_EVENT,
  THEME_MODE_CHANGE_EVENT,
  CUSTOM_BACKGROUND_CHANGE_EVENT,
  HIDE_BACKEND_CONSOLE_CHANGE_EVENT,
  CACHE_BROWSER_FONT_SIZE_CHANGE_EVENT,
  getBackendProfile,
  getBackendProfileNames,
  resolveSelectedBackendProfile,
  getSelectedBackendProfileJobPayload,
  getDefaultBackendProfile,
  setDefaultBackendProfile,
  getSelectedBackendProfile,
  getSelectedBackendProfileDisplay,
  setSelectedBackendProfile,
  hasExplicitBackendProfile,
  fetchBackendProfiles,
  fetchBackendProfile,
  createBackendProfile,
  updateBackendProfile,
  deleteBackendProfile,
  getSelectedTranslatorTemplate,
  setSelectedTranslatorTemplate,
  getHomeHistoryRetentionLimit,
  setHomeHistoryRetentionLimit,
  getHomeJobRetentionLimit,
  setHomeJobRetentionLimit,
  getCacheBrowserFontSizePreference,
  setCacheBrowserFontSizePreference,
  getHideBackendConsolePreference,
  setHideBackendConsolePreference,
  getThemeModePreference,
  setThemeModePreference,
  getCustomBackgroundPreference,
  setCustomBackgroundPreference,
  clearCustomBackgroundPreference,
  loadPromptTemplateOverrides,
  savePromptTemplateOverrides,
  getPromptTemplateOverride,
  setPromptTemplateOverride,
  deletePromptTemplateOverride,
  getPromptTemplateOverridesForJob,
} from './preferences';
